# Generated by Django 5.2.6 on 2025-10-20 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, help_text='Nombre único de la categoría', max_length=100, unique=True, verbose_name='Nombre de categoría')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la categoría', verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la categoría está activa', verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('correo', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Es staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Es superusuario')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del pedido')),
                ('total_pedido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total del pedido')),
                ('estado_pedido', models.CharField(choices=[('pendiente_pago', 'Pendiente de Pago'), ('pagado', 'Pagado'), ('preparando', 'Preparando Envío'), ('enviado', 'Enviado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], db_index=True, default='pendiente_pago', max_length=50, verbose_name='Estado del pedido')),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('webpay', 'Webpay'), ('efectivo', 'Efectivo')], default='transferencia', max_length=50, verbose_name='Método de pago')),
                ('nombre_cliente', models.CharField(max_length=255, verbose_name='Nombre del cliente')),
                ('correo_cliente', models.EmailField(max_length=254, verbose_name='Correo del cliente')),
                ('telefono_cliente', models.CharField(max_length=20, verbose_name='Teléfono del cliente')),
                ('direccion', models.CharField(max_length=500, verbose_name='Dirección')),
                ('region', models.CharField(max_length=100, verbose_name='Región')),
                ('comuna', models.CharField(max_length=100, verbose_name='Comuna')),
                ('codigo_postal', models.CharField(blank=True, max_length=20, verbose_name='Código postal')),
                ('referencia_direccion', models.TextField(blank=True, help_text='Referencias adicionales para encontrar la dirección', verbose_name='Referencia')),
                ('notas_pedido', models.TextField(blank=True, help_text='Notas o comentarios del cliente', verbose_name='Notas del pedido')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('numero_seguimiento', models.CharField(blank=True, help_text='Número de seguimiento del envío', max_length=100, verbose_name='Número de seguimiento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedidos',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=100, verbose_name='Nombre del producto')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripción')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio en pesos chilenos', max_digits=10, verbose_name='Precio unitario')),
                ('unidad_medida', models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramo'), ('gr', 'Gramo'), ('lt', 'Litro'), ('ml', 'Mililitro'), ('paquete', 'Paquete'), ('caja', 'Caja')], default='unidad', max_length=20, verbose_name='Unidad de medida')),
                ('stock_disponible', models.IntegerField(default=0, help_text='Cantidad disponible en inventario', verbose_name='Stock disponible')),
                ('imagen', models.ImageField(blank=True, help_text='Imagen principal del producto', null=True, upload_to='productos/%Y/%m/', verbose_name='Imagen del producto')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el producto está activo para venta', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='miapp.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_oferta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de oferta')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha de fin')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la oferta está activa', verbose_name='Activa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='miapp.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
                'db_table': 'ofertas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio_compra', models.DecimalField(decimal_places=2, help_text='Precio al momento de la compra (snapshot)', max_digits=10, verbose_name='Precio de compra')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='miapp.pedido', verbose_name='Pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='miapp.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de pedido',
                'verbose_name_plural': 'Detalles de pedidos',
                'db_table': 'detalle_pedidos',
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['-fecha_pedido'], name='pedidos_fecha_p_6d244f_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado_pedido'], name='pedidos_estado__75d753_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['usuario', '-fecha_pedido'], name='pedidos_usuario_50cdcd_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='productos_nombre_d31432_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria', 'activo'], name='productos_categor_6d98d4_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['-fecha_creacion'], name='productos_fecha_c_158c82_idx'),
        ),
        migrations.AddIndex(
            model_name='oferta',
            index=models.Index(fields=['producto', 'fecha_inicio', 'fecha_fin'], name='ofertas_product_e22b83_idx'),
        ),
        migrations.AddIndex(
            model_name='detallepedido',
            index=models.Index(fields=['pedido'], name='detalle_ped_pedido__f36811_idx'),
        ),
        migrations.AddIndex(
            model_name='detallepedido',
            index=models.Index(fields=['producto'], name='detalle_ped_product_a29678_idx'),
        ),
    ]
