# Generated by Django 5.2.6 on 2025-10-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen principal del producto', null=True, upload_to='productos/', verbose_name='Imagen del producto'),
        ),
    ]
