# Generated by Django 5.2.6 on 2025-11-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
    ]
